Seleniun pracs
Boomfield/Java-Selenium-Task pull request #1
Opened 2022-06-07 09:42 UTC by Boomfield

2022-06-07 09:43 UTC, HeyBanana commented on MySelenium/pom.xml
> +    <properties>
why do you need this?

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/main/java/MySelenium.java
> +public class MySelenium {
delete

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/main/java/driver/config/BaseDriverConfig.java
> +    public abstract WebDriver creatDriver ();
typo: creatDriver -> createDriver

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +            driver.manage().window().maximize();
you already have maximize in .creatDriver

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/main/java/driver/config/ChromeDriverConfig.java
> +@Override
add space

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/main/java/driver/config/ChromeDriverConfig.java
> +        driver.manage().window().maximize();
[15-17] move to base class, because it`s duplicated in one more place (FirefoxDriverConfig )

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/main/java/driver/config/ChromeDriverConfig.java
> +        System.setProperty("webdriver.chrome.driver", "C:\\P\\IntelliJ IDEA Community Edition 2021.3.1\\JavaPractical\\MySelenium\\drivers\\chromedriver.exe");
add "C:\\P\\IntelliJ IDEA Community Edition 2021.3.1\\JavaPractical\\MySelenium\\drivers\\chromedriver.exe" to config or environment variables. cause it`s local path only on your machine

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/main/java/driver/config/FirefoxDriverConfig.java
> +public class FirefoxDriverConfig extends BaseDriverConfig{
same fixes for this class as for ChromeDriverConfig

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/main/java/helpers/PropertyHelper.java
> +            FileInputStream inputStream = new FileInputStream("C:\\P\\IntelliJ IDEA Community Edition 2021.3.1\\JavaPractical\\MySelenium\\src\\test\\resources\\"+fileName);
change file path. it`s suitable only for your machine

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/main/java/helpers/PropertyHelper.java
> +
delete space

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/main/java/wait/Waiter.java
> +
delete extra spaces

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/main/java/wait/Waiter.java
> +        timer.schedule(timerTask,seconds);
undo

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/configuration/Constants.java
> +public class Constants {
rename -> SiteProperties

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/listeners/TmpSuiteListener.java
> +        PropertyHelper.initProperty("config.prod.properties");
should be possible to substitute another environment config.{env}.properties

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigatorPage.java
> +        search.sendKeys(title);
create In Driver wrapper method for this - EnterText

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigatorPage.java
> +        ArrayList<String> allResultElements = driver.findElements(topicSearchResultLabel).stream().map(x -> x.getText()).collect(toCollection(ArrayList::new));
make method in driver

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/pages/component/CookieComponent.java
> +        buttonCloseCookie.click();
make Click method in driver

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/pages/component/CookieComponent.java
> +    By buttonCookie = By.xpath("//button[@id = 'truste-consent-required']");
public

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/pages/BasePage.java
> +    public BasePage(Driver driver) {
formatting

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/steps/BaseSteps.java
> +    Driver driver;
protected

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/steps/NavigatorSteps.java
> +    public void textEqualTopicList (String findElement) {
rename -> VerifyAllTopicSearchResultsContains(string text)

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/steps/NavigatorSteps.java
> +    NavigatorPage navigatorPage = new NavigatorPage(driver);
private

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/steps/NavigatorSteps.java
> +        Assert.assertTrue(navigatorPage.getTopicSearchResults().stream().allMatch(x->x.toLowerCase().contains(findElement.toLowerCase())));
use hamcrest for assertions. watch video or read documentation. after adding harmrest u can create own assert method if it does not have such

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/tests/AppTest.java
> +        Thread.sleep(2000);
delete

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/tests/AppTest.java
> +        driver.navigate(PropertyHelper.getProperty("url"));
use your constants

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/tests/AppTest.java
> +        cookieComponent.closeCookie();
create new class SapNavigation. in this class create method - OpenPageAndAcceptCookies and put there navigate() and closeCookie()

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/tests/AppTest.java
> +    Driver driver = new Driver(new ChromeDriverConfig());
try not to use driver in test. only pages and steps. put to BaseTest class

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/java/tests/AppTest.java
> +        navigatorSteps.textEqualTopicList(findElement);
it`s better to add logical spaces between verifies and actions

2022-06-07 10:10 UTC, HeyBanana commented on MySelenium/src/test/resources/config.prod.properties
> +url=https://developers.sap.com/tutorial-navigator.html
change

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/main/java/asserts/AssertContainsToLowerCase.java
> +public class AssertContainsToLowerCase extends TypeSafeDiagnosingMatcher <ArrayList<String>> {
it can be deleted.

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/main/java/component/Locator.java
> +
extra space

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +    public static ThreadLocal<Driver> instance = new ThreadLocal<>();
you can create method getDriver which should return instance.value

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +    public WebDriver getDriver() {
can be private and renamed in case if you will create another getDriver method

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +    }
try ti make only one return in this method

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +    public void enterText (Locator locator,String text) {
space

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/main/java/driver/config/BaseDriverConfig.java
> +    public Duration TimePageLoad ;
code convention

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/main/java/driver/config/BaseDriverConfig.java
> +    public void waitElementAndPage (WebDriver driver){
rename -> configureWaits

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/main/java/driver/config/ChromeDriverConfig.java
> +        System.setProperty("webdriver.chrome.driver", "C:\\P\\IntelliJ IDEA Community Edition 2021.3.1\\JavaPractical\\MySelenium\\drivers\\chromedriver.exe");
fix it

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/main/java/helpers/PropertyHelper.java
> +            FileInputStream inputStream = new FileInputStream("src\\test\\resources\\" + fileName);
pass full path to fileName (dot use "src\\test\\resources\\" here)

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/main/java/wait/Waiter.java
> +                        Thread.sleep(500);
make it 200

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/configuration/Constants.java
> +public class Constants {
SiteProperties

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/configuration/Constants.java
> +    public static final String SiteProperties = PropertyHelper.getProperty("url");
public static final String Url

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/data/ConstantPage.java
> +public class ConstantPage {
rename PageUrls

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/listeners/TmpSuiteListener.java
> +        PropertyHelper.initProperty("config."+env+".properties");
make as string interpolation

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/pages/BasePage.java
> +        return new Locator(By.xpath(xPathElement),by);
aligning

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/pages/BasePage.java
> +    public Locator getLocator (String xPathElement) {
rename byXpath

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigatorPage.java
> +    public FilterFacet topic = new FilterFacet(By.xpath("(//div[contains(@class,'FilterFacets__filterFacetsColumn')])[1]"));
rename topicFacetSection

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigatorPage.java
> +    public Locator allPageNumber = getLocator( "//a[contains(@class,'PageLink__pageLink')]");
rename -> paginationNumberLink

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigatorPage.java
> +        listAllNumberPageLink.get(pageNumber).click();
38-39 rows -> make corresponding method in Driver

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigatorPage.java
> +    public void clickTopicFilter (TypeFilterTitle nameFilter) {
move this methjod to FilterFacet

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigatorPage.java
> +        Driver.instance.get().findElement(getLocator(String.format("//span[.='%s']", nameFilter))).click();
make method that returns this locator

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigatorPage.java
> +    public void clickPageLinkNumber (int pageNumber) {
clickPaginationLinkByNumber

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/pages/component/CookieComponent.java
> +    public String buttonCookie = "//button[@id = 'truste-consent-required']";
leave one

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/pages/component/FilterFacet.java
> +    public Locator resultLabelBy = getLocator(".//div[@class='simplebar-content']//span");
make css

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/pages/component/Title.java
> +public class Title extends BasePage {
ResultItem

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/pages/helpers/TypeTitle.java
> +public enum TypeTitle {
delete

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/pages/helpers/TypeFilterTitle.java
> +public enum TypeFilterTitle {
ExperienceType

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/steps/NavigatorSteps.java
> +   public Title title = new Title();
this component exists in NavigatorPage

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/steps/NavigatorSteps.java
> +            Assert.assertTrue(condition);
add second parameter as message. and use harmrest

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/steps/NavigatorSteps.java
> +            boolean condition = Waiter.wait(()->Driver.instance.get().getResultTextList(title.headerTitle).stream().allMatch(x->x.equals(nameFilter.toString())),10);
this indeed does not look good, u can use instead another wait - for result absence after click
 navigatorPage.clickPageLinkNumber(i);
Waiter.wait(() => !title.headerTitle.Exist)

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/steps/NavigatorSteps.java
> +            boolean condition = Waiter.wait(()->Driver.instance.get().getResultTextList(title.headerTitle).stream().allMatch(x->x.equals(nameFilter.toString())),10);
use static include to avoid Driver.

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/tests/AppTest.java
> +public class AppTest extends BaseTest{
rename test class

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/tests/AppTest.java
> +    private String findElement = "abap";
rename => searchFilterText

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/tests/BaseTest.java
> +    private static BaseDriverConfig baseDriverBuilder = new ChromeBuilder().withTimePageLoad(60).withTimeElementWait(40).build();
implement factory pattern for this
at the end of the day it will be driverConfigFactory.getConfig(BrowserType.Chrome)

2022-06-18 19:43 UTC, HeyBanana commented on MySelenium/src/test/java/tests/BaseTest.java
> +        Thread.sleep(2000);
delete

2022-06-18 19:57 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigatorPage.java
> +        Driver.instance.get().findElement(getLocator(String.format("//span[.='%s']", nameFilter))).click();
use click ethod

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/main/java/asserts/AssertContainsToLowerCase.java
> +public class AssertContainsToLowerCase extends TypeSafeDiagnosingMatcher <ArrayList<String>> {
delete class

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +    private WebDriver getStandardDriver() {
getNativeDriver sounds better

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +    }
fix it

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +    public void clickByText(Locator locator, String nameFilter) {
String nameFilter -> String text

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +        ArrayList <WebElement> listFilterEqualsNameF = Driver.getDriver().findElements(locator)
listFilterEqualsNameF  -> elements

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +                .stream().filter(x->x.getText().equals(nameFilter)).collect(toCollection(ArrayList::new));
use findFirst

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +    public void clickPaginationByIndex(int pageNumber, Locator locator) {
clickPaginationByIndex -> clickElementByIndex(int index...)

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/main/java/driver/config/BaseDriverConfig.java
> +    public Duration TimePageLoad;
code convention

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/main/java/driver/config/BaseDriverBuilder.java
> +   protected BaseDriverConfig baseDriverConfig;
formatting

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/test/java/listeners/TmpSuiteListener.java
> +        PropertyHelper.initProperty(String.format("src\\test\\resources\\config.%s.properties",env));
formatting

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/test/java/pages/BasePage.java
> +    public Locator getLocatorByXpath(String xPathElement) {
getLocatorByXpath -> byXpath

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/test/java/pages/BasePage.java
> +    public Locator getLocatorByCssSelector(String xPathElement) {
byCss(String css)

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigatorPage.java
> +    public FilterFacet experienceFacetSection = new FilterFacet(By.xpath("(//div[contains(@class,'FilterFacets__filterFacetsColumn')])[3]"));
experience doest not have search input, so it`s different type of section

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/test/java/pages/component/FilterFacet.java
> +        Driver.getDriver().enterText(filterSearchBy, title);
use static import

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/test/java/steps/NavigatorSteps.java
> +    public void VerifyAllHeaderExpResultsContains (ExperienceType nameFilter){
dotnt use contractions - Exp

2022-06-21 13:31 UTC, HeyBanana commented on MySelenium/src/test/java/tests/TestTutorialPage.java
> +    public void shouldAnswerWithTrue1() {
rename tests

2022-06-21 14:28 UTC, Boomfield commented on MySelenium/src/test/java/pages/NavigatorPage.java
> +    public FilterFacet experienceFacetSection = new FilterFacet(By.xpath("(//div[contains(@class,'FilterFacets__filterFacetsColumn')])[3]"));
need new class FilterFacetNotSearch?

2022-08-16 13:06 UTC, HeyBanana requested changes

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/.allure/allure-2.0.1/config/allure-junit.yml
> +plugins:
i am not sure that u need these folders in git. Maybe should be added to gitignore
![image](https://user-images.githubusercontent.com/22958586/183035767-c4e297ea-7820-44fa-93c8-9f07aa35219c.png)

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
delete it from your project 
![image](https://user-images.githubusercontent.com/22958586/183036264-918d15ab-95a4-4afa-8dc1-5ed7ed5764d6.png)

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +        return Driver.instance.get();
delete this part Driver.

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +    private By firstIFrame = null;
rename -> currentFrame

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +    public ArrayList<String> getResultTextList(Locator locator) {
rename -> getElementsText

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +        Optional<WebElement> element = Driver.getDriver().findElements(locator)
delete Driver.getDriver

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +    public void clickPaginationByIndex(int index, Locator locator) {
rename -> clickElementByIndex
and make renaming in method

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/main/java/driver/Driver.java
> +        WebElement search = findElement(locator);
search -> element

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/main/java/driver/config/ChromeDriverConfig.java
> +
extra line

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/main/java/driver/config/DriverConfigFactory.java
> +                return null;
throw exception here

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/main/java/driver/config/FirefoxDriverConfig.java
> +    @Override
add empty line

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/main/java/helpers/BrowserType.java
> +
delete line

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/main/java/helpers/BrowserType.java
> +package helpers;
put it under driver/config folder

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/configuration/SiteProperties.java
> +    public static final String URLSAPDEVELOPER = PropertyHelper.getProperty("urlSapDeveloper");
as i know there is such convention: URL_SAP_DEVELOPER (DEVELOPERS_URL - better)

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/configuration/SiteProperties.java
> +    public static final String FASTURL = PropertyHelper.getProperty("urlFast");
delete it from here and resource file and put such url in PageUrls

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/configuration/SiteProperties.java
> +public class SiteProperties {
rename ConfigProperties

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/BasePage.java
> +    public Locator getLocatorByXpath(String byXpath1) {
String byXpath1 -> xpath

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/BasePage.java
> +    public Locator getLocatorByXpath(String byXpath1) {
i would be make it smaller -> getByXpath, getByCss

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/FrameContactAsForm.java
> +package pages;
make such structure
pages
---contactUs
------helpers
--------ContactFormRelationshipToSap
--------ContactFormTopicType
--------Form
------FrameContactAsForm
---tutorialNavigator
------...
------...

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/FrameContactAsForm.java
> +public class FrameContactAsForm extends BasePage {
ContactUsForm

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/FrameContactAsForm.java
> +    public Locator relationshipToSap = getLocatorByXpath("(//div[contains(@class,'form-group')])[31]");
relationshipToSap  -> relationshipToSapDropdown
change xpath //div[contains(@class, 'ormio-component-RelationshipToSAP')]/input

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/FrameContactAsForm.java
> +    public Locator companyName = getLocatorByCss("#CompanyName");
companyNameInput
rename other fields

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/FrameContactAsForm.java
> +    public Locator titleOfQuestion = getLocatorByXpath(".//div[contains(@class,'formio-component-TopicArea')]");
titleOfQuestion -> topicDropdown

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/FrameContactAsForm.java
> +    public Locator firstTitleInList = getLocatorByXpath("(//div[contains(@class,'choices__item choices__item--choice choices__item--selectable')])[1]");
no need to specify [1] in xpath. anyway selenium finds first element

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/FrameContactAsForm.java
> +        getDriver().clickByText(getLocatorByXpath("//div[contains(@id,'choices--RelationshipToSAP-item-choice')]"), contactFormRelationshipToSap.toString());
make field for xpath

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/FrameContactAsForm.java
> +    public void enterFirstName(Form form) {
string firstName
below the same

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigationSap.java
> +    public void removeCookie() {
rename -> acceptCookie

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigationSap.java
> +        cookieComponent.closeCookie();
delete this row

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigationSap.java
> +        getDriver().driver.manage().addCookie(cookie1);
create addCookie method in driver

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/NavigationSap.java
> +public class NavigationSap extends BasePage {
it`s not a page so should not be under pages folder

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/SapPage.java
> +public class SapPage extends BasePage {
ContactUsWidget

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/SapPage.java
> +    public Locator contactForm = getLocatorByXpath("//a[contains(@class,'Title__titleInContactModule')]");
formOpenLink

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/SapPage.java
> +    public Locator contactContainer = getLocatorByXpath("//div[contains(@class,'Flyout__opener')]");
collapsedSection

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/SapPage.java
> +    public Locator closeContactForm = getLocatorByXpath("//div[@class='toolbtn exit icon-close mfp-close']");
closeWidgetIcon

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/component/CookieComponent.java
> +public class CookieComponent extends BasePage {
delete

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/helpers/Form.java
> +public class Form {
ContactUsForm

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/pages/helpers/StringHelper.java
> +package pages.helpers;
move it to src/helpers

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/steps/BaseSteps.java
> +public class BaseSteps {
delete

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/tests/TestSapPage.java
> +public class TestSapPage extends BaseTest {
ContactUsTests

2022-08-16 13:06 UTC, HeyBanana commented on MySelenium/src/test/java/tests/TestSapPage.java
> +
add comment // Verify was not added not to submit test data for production

2022-08-26 11:05 UTC, closed without merging